# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rudolf Panka irodalomterapeuta honlapja
tagline: Irodalmi műveken át az önismeretig
author: Rudolf Panka
email: info@rudolfpanka.hu
description: >- # this means to ignore newlines until "baseurl:"
  Rudolf Panka irodalomterapeuta honlapja: a legkülönfélébb irodalmi műveket választom ki ahhoz, hogy segítségükkel elkezdhesd a saját életed történetét írni, aminek te vagy a főszereplője! Legyen szó egyéni konzultációról, önismereti csoportról vagy workshopról, a szövegek és én leszünk társaid az úton önmagadhoz!
baseurl: '/' # the subpath of your site, e.g. /blog
url: "https://www.rudolfpanka.hu" # the base hostname & protocol for your site, e.g. http://example.com
lang: hu_HU
twitter_username: 
github_username: si0rac
facebook:
  admins: 
logo: "/assets/icons/main-logo-large-white.png"
social:
  links: 
    - https://www.facebook.com/pages/category/Community/Rudolf-Panka-biblioterapeuta-%C3%B6nismeret-irodalom-263008247482207/

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-menus
- jekyll-redirect-from
- jekyll-seo-tag
  
collections:
  articles:
    output: true
    permalink: "/:path/"
  images: 
    output: true
  events:
    output: true
    permalink: "/:path/"

defaults:
- scope:
    path: ''
    type: articles
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    layout: default


algolia:
  index_name: BIBLIO_TEST
  application_id: 9AYJ75P776

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
