---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Deployment
- type: document
  path: deploy.md
  label: Deploying the site
- type: heading
  label: Content
- type: document
  path: _layouts/index.html
  label: Kezdőlap (HTML)
- type: document
  path: _articles/index.md
  label: Kezdőlap (markdown)
- type: document
  path: _articles/about.md
  label: Rólam
- type: document
  path: _articles/events.md
  label: Események (menüpont)
- type: directory
  path: _events
  label: Események (az egyes események)
  create: all
  match: "**/*"
  new_doc_ext: ".md"
  templates:
  - events
- type: document
  path: _articles/groups.md
  label: Csoportok
- type: jekyll-posts
  label: Blogposztok
  create: all
  templates:
  - blogposts
- type: document
  path: _includes/contact.html
  label: Kapcsolat
- type: directory
  path: _images
  label: Images
  create: all
  match: "**/*"
- type: document
  path: _layouts/default.html
  label: Default layout
  read_only: true
upload_dir: media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --watch --port 8080 --host 0.0.0.0
    -d _site
